### ISSUE TITLE
high cpu usage in WaitForCardPresent 

### ISSUE THREAD

**Issue by mrfelfel** [sf1/go-card#3]
in  WaitForCardPresent function for first card 
cpu usage is 12% 

[example](https://github.com/sf1/go-card/blob/master/examples/show-atr/main.go)

in [my example](https://github.com/mrfelfel/go-card-example/blob/master/main.go)

after than read first card , cpu usage is not high 

why ?

**Comment by sf1** [comment]
When running your example on my Windows system, the CPU usage is close to 0% and has no issue. Can you provide the following details?

1. Operating system version
2. Card reader model
3. Go version used to build/run the example.

**Comment by sf1** [comment]
I reproduced the problem and commited a fix. Thanks for reporting.

**Comment by sf1** [comment]
I also added a new method called reader.WaitUntilCardRemoved. See the [updated atr example here](https://github.com/sf1/go-card/blob/master/examples/show-atr/main.go)

**Comment by mrfelfel** [comment]
tnx
