### ISSUE TITLE
Not compatible with OS X

### ISSUE THREAD

**Issue by pzeinlinger** [sf1/go-card#4]
I really like the idea of not having to rely on cgo.
Unfortunately, there is currently no socket provided by the securityd (which implements pcsc-lite on a mac). The connection to net.Dial("unix","/var/run/pcscd/pcscd.comm") fails.

Any idea who we could resolve this?

**Comment by sf1** [comment]
I currently don't have any devices running OS X, but if you (or anyone reading this) finds an approach that would work, please let me know.

**Comment by sf1** [comment]
There doesn't seem to be a way to add MacOS support without resorting to cgo
