### ISSUE TITLE
context for WaitForCardPresent

### ISSUE THREAD

**Issue by Caledfwlch1** [sf1/go-card#5]
Hello, Sebastian!
Thank you very much for the package!
Could you please add context to WaitForCardPresent method.

I expect something like this:
`
func (ctx *Context) WaitForCardPresent(pctx context.Context) (*Reader, error) {
	var reader *Reader
	for reader == nil {
		select {
		case <-pctx.Done():
			return nil, pctx.Err()
		default:
		}

`

**Comment by sf1** [comment]
Hi, could you explain the use case? I am not sure what the motivation for another context is. Are you looking for something like a timeout or cancel feature?
